name: Django CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: project_gallery.settings
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file for testing
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DEBUG=True" >> .env
          echo "ALLOWED_HOSTS=127.0.0.1,localhost" >> .env
          echo "DB_NAME=db.sqlite3" >> .env

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: project_gallery.settings
        run: pytest